import NavigationMenu from "@/Components/NavigationMenu/NavigationMenu"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigationMenu/>
        {children}
        </body>
    </html>
  )
}
